{% set name = "EbookLib" %}
{% set version = "0.17.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "fe23e22c28050196c68db3e7b13b257bf39426d927cb395c6f2cc13ac11327f1" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - lxml
    - six

test:
  imports:
    - ebooklib
    - ebooklib.plugins

about:
  home: https://github.com/aerkalov/ebooklib
  license: AGPL 3.0
  license_file: LICENSE.txt
  summary: 'Ebook library which can handle EPUB2/EPUB3 and Kindle format'
  doc_url: https://github.com/aerkalov/ebooklib/wiki
  dev_url: https://github.com/aerkalov/ebooklib

extra:
  recipe-maintainers:
    - pmlandwehr
