{% set name = "ebooklib" %}
{% set version = "0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EbookLib-{{ version }}.tar.gz
  sha256: 38562643a7bc94d9bf56e9930b4927e4e93b5d1d0917f697a6454db5a1c1a533

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - lxml
    - six

test:
  imports:
    - ebooklib
    - ebooklib.plugins
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aerkalov/ebooklib
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: 'Ebook library which can handle EPUB2/EPUB3 and Kindle format'
  doc_url: https://github.com/aerkalov/ebooklib/wiki
  dev_url: https://github.com/aerkalov/ebooklib

extra:
  recipe-maintainers:
    - rxm7706
    - pmlandwehr
