{% set name = "EbookLib" %}
{% set version = "0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 07e9b4db0a30c73623b14e23b315634a450d2c13f23d1dba4b457a6ca16a58be

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - lxml
    - six

test:
  imports:
    - ebooklib
    - ebooklib.plugins

about:
  home: https://github.com/aerkalov/ebooklib
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: 'Ebook library which can handle EPUB2/EPUB3 and Kindle format'
  doc_url: https://github.com/aerkalov/ebooklib/wiki
  dev_url: https://github.com/aerkalov/ebooklib

extra:
  recipe-maintainers:
    - pmlandwehr
