{% set name = "EbookLib" %}
{% set version = "0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38562643a7bc94d9bf56e9930b4927e4e93b5d1d0917f697a6454db5a1c1a533

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - lxml
    - six

test:
  imports:
    - ebooklib
    - ebooklib.plugins

about:
  home: https://github.com/aerkalov/ebooklib
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Ebook library which can handle EPUB2/EPUB3 and Kindle format
  doc_url: https://github.com/aerkalov/ebooklib/wiki
  dev_url: https://github.com/aerkalov/ebooklib

extra:
  recipe-maintainers:
    - pmlandwehr
